### ISSUE TITLE
Formatting for units in parameter description

### ISSUE THREAD

**Issue by toddkarin** [hackingmaterials/pv-terms#5]
What format is best for units, E.g. Watts vs. W vs. watts?

**Comment by cwhanse** [comment]
I'd prefer the SI symbol rather than the SI unit name, e.g. W for watt. With exceptions for special characters (degree C) we can follow this [convention](https://en.wikipedia.org/wiki/International_System_of_Units) for writing symbols.  I like the way units are rendered on readthedocs e.g. **[W]** but I don't know how to make that happen here.

**Comment by kandersolar** [comment]
I'd recommend another CSV column for units that gets its own rendering similar to how the deprecated names are treated.  +1 for [W] and SI symbols

**Comment by toddkarin** [comment]
Sounds good. Two ways to accomplish this:
a. Use inline markup in the description column.
b. Make a new column 'Dimensions' and format this for each element in the list

Option a allows each description to place the unit in the most readable location e.g. 

- surface_azimuth: Surface azimuth angles in **decimal degrees**. The azimuth convention is defined as degrees east of north (e.g. North=0, South=180, East=90, West=270)

Then the unit doesn't have to be in the same place in every description. Compare to option b: e.g.

- surface_azimuth: **[degrees]**. Surface azimuth angles. The azimuth convention is defined as degrees east of north (e.g. North=0, South=180, East=90, West=270)

**Comment by toddkarin** [comment]
Decided to use option b.
